#!/usr/bin/env python
import time
import sys
import tfidf
import answer_finding
import question_classification
import grammar_util    
import normalize
import codecs
article_name = sys.argv[1]
query_name = sys.argv[2]

num_sentences = 5

start_time = time.time()
def generate_query(text):
    query_tree = answer_finding.parser.raw_parse(text).next()
    return query_tree

with codecs.open(query_name, encoding="utf-8", errors='ignore') as query_f:
    queries = query_f.readlines()
scoring_function = tfidf.tfidf(article_name)
query_trees = map(lambda q: normalize.normalize(generate_query(q)), queries)
sentences_lists = map(lambda x: scoring_function(x, num_sentences), queries)

results = map(lambda (sents, query): answer_finding.select_answer(sents, query, start_time), zip(sentences_lists, query_trees))


for i in results:
    i.encode('utf-8')
    print i
